apiVersion: v1
kind: Service
metadata:
  name: molecule-service
  labels:
    app: molecule
spec:
  selector:
    app: molecule
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9090
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090
